name: Compile test

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install toolchain
      run: |
        sudo apt update
        sudo apt install gcc-arm-none-eabi

    - name: Build the application
      run: make -C firmware BOARD=m4a-mb
