APPLICATION ?= tests_$(notdir $(patsubst %/,%,$(CURDIR)))

ifneq (,$(wildcard $(CURDIR)/tests*/.))
  DEFAULT_MODULE += test_utils_interactive_sync
  # add interactive test configuration when testing Kconfig
  ifeq (1,$(TEST_KCONFIG))
    KCONFIG_ADD_CONFIG += $(RIOTBASE)/tests/test_interactive.config
  endif
endif

ifneq (,$(filter tests_driver_%,$(APPLICATION)))
  BOARD ?= m4a-mb
endif

BOARD ?= m4a-mb
RIOTBASE ?= $(CURDIR)/../RIOT
QUIET ?= 1

# DEVELHELP enabled by default for all tests, set 0 to disable
DEVELHELP ?= 1