name: build-docs
on:
  push:
    branches:
      - "main"
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt install doxygen graphviz

      - name: Build docs
        run: |
          cd doc/doxygen
          make

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: doc/doxygen/html
